name: "protostar"
description: "Generate changelog using protostar binary"

inputs:
  version:
    description: "Version string for this release"
    required: true
  template:
    description: "Path to the markdown template"
    required: false
    default: "templates/changelog_template.md"
  args:
    description: "Additional flags to pass to the binary"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Download protostar binary
      shell: bash
      run: |
        mkdir -p $GITHUB_ACTION_PATH/bin
        curl -sSL "https://github.com/stellayazilim/Protostar/releases/download/v0.1.39/protostar" \
          -o $GITHUB_ACTION_PATH/bin/protostar
        chmod +x $GITHUB_ACTION_PATH/bin/protostar

    - name: Run Protostar
      shell: bash
      run: |
        $GITHUB_ACTION_PATH/bin/protostar \
          --version "${{ inputs.version }}" \
          --template "${{ inputs.template }}" \
          ${{ inputs.args }}