name: "protostar"
description: "Generate changelog using protostar binary"

inputs:
  version:
    description: "Version string for this release"
    required: true
  template:
    description: "Path to the markdown template"
    required: false
    default: "templates/changelog_template.md"
  args:
    description: "Additional flags to pass to the binary"
    required: false
    default: ""
outputs:
  stdout:
    description: "stdout"
runs:
  using: "composite"
  steps:
    - name: Download protostar binary
      shell: bash
      run: |
        mkdir -p $GITHUB_ACTION_PATH/bin
        curl -sSL "https://github.com/stellayazilim/Protostar/releases/download/v0.1.39/protostar" \
          -o $GITHUB_ACTION_PATH/bin/protostar
        chmod +x $GITHUB_ACTION_PATH/bin/protostar

    - name: Run Protostar and capture stdout
      id: run_protostar
      shell: bash
      run: |
        OUTPUT=$($GITHUB_ACTION_PATH/bin/protostar \
          --version "${{ inputs.version }}" \
          --template "${{ inputs.template }}" \
          "${{ inputs.args }})"
        echo "$OUTPUT"
        echo "stdout<<EOF" >> $GITHUB_OUTPUT
        echo "$OUTPUT" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT