name: "protostar"
description: "Generate changelog using protostar binary"

inputs:
  version:
    description: "Version string for this release"
    required: true
  output:
    description: "Output file path"
    required: false
  template:
    description: "Path to the markdown template"
    required: false
    default: "templates/changelog_template.md"
  args:
    description: "Additional flags to pass to the binary"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Download protostar binary
      shell: bash
      run: |
        mkdir -p $GITHUB_ACTION_PATH/bin
        curl -sSL "https://github.com/stellayazilim/Protostar/releases/download/v0.1.38/protostar" \
          -o $GITHUB_ACTION_PATH/bin/protostar
        chmod +x $GITHUB_ACTION_PATH/bin/protostar

    - name: Run protostar
      shell: bash
      run: |
        $GITHUB_ACTION_PATH/bin/protostar  --version ${{ inputs.version }} --template ${{ inputs.template }} ${{ inputs.args }} > "${{inputs.output}}"
    - name: Commit generated file
      shell: bash
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add ${{inputs.output}}
        git commit -m "Update changelog"
        git push origin HEAD:main
