name: "Protostar Changelog"
description: "Generate changelog using binary artifact"
inputs:
  args:
    description: "Additional flags to pass to the binary, e.g. -version v0.0.3 -output CHANGELOG.md"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Download Protostar binary artifact
      uses: actions/download-artifact@v4
      with:
        name: protostar
        path: ./bin

    - name: Run Protostar
      run: |
        chmod +x ./bin/protostar
        ./bin/protostar \
          ./bin/protostar ${{ inputs.args }}