name: build
on:
  push:
    tags:
      - v*

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: stella/protostar/.github/workflows/test.yml@main
        id: test_run

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25'

      - name: pass_test
        if: ${{ test_run.outputs.success == 'success' }}
        run: |
          echo "Tests did not pass or no tag exists. Stopping workflow."
          exit 1

      - name: Build binary
        run: |
          mkdir -p build
          GOOS=linux GOARCH=amd64 go build -o build/protostar main.go
          chmod +x build/protostar

      - name: Upload to release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.context }}
          files: ./build/protostar