name: build
on:
  workflow_run:
    workflows: ["test"]
    branches: [main]
    types:
      - completed

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}  # checkout the commit that triggered tests
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25'

      - name: Build binary
        run: |
          GOOS=linux GOARCH=amd64 go build -o build/protostar main.go
          chmod +x build/protostar


      - name: Upload to release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.workflow_run.head_branch }}  # use the tag pushed upstream
          files: ./build/protostar