name: build
on:
  workflow_run:
    workflows: ["test"]
    branches: [main]
    types:
      - completed

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25'

      - name: Build binary
        run: |
          GOOS=linux GOARCH=amd64 go build -o generate-changelog main.go
          chmod +x generate-changelog

      - name: Build binary
        run: |
          GOOS=linux GOARCH=amd64 go build -o generate-changelog main.go
          chmod +x generate-changelog

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: generate-changelog
          path: generate-changelog
