name: test
on:
  workflow_call:
    outputs:
      success:
        description: 'Tests passed'
        value: $${{jobs.test.outputs.success}}
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      success: ${{steps.run_tests.outputs.success}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25'

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests
        id: run_tests
        run: |
          TEST_OUTPUT=$(go test ./... -v -cover 2>&1)
          echo "$TEST_OUTPUT"
          if echo "$TEST_OUTPUT" | tail -n 1 | grep -q "^FAIL"; then
            echo "success=false" >> $GITHUB_OUTPUT
          else
            echo "success=true" >> $GITHUB_OUTPUT
          fi
        shell: bash